In [2]:
import numpy as np

In [8]:
#行列Aの定義
A = np.matrix([[3., 1., 2.], [2., 3., 1.]])

print("行列Aの大きさ(M行， N行): ", np.shape(A))
print("A= \n", A)

#スカラー倍
c =2.
print("cA= \n",c* A)

#行列Aに行列Bを足す
B = np.matrix([[-1., 2., 4.], [1., 8., 6.]])
print("A + B= \n", A+B)

#行列Aに行列Bを掛ける
B = np.matrix([[4., 2.], [-1., 3.], [1., 5.]])
print("AB= \n", np.matmul(A,B))
print("AB= \n", np.einsum("mk,kn->mn",A,B))

#行列Aと行列Bのアダマール積(要素ごとの積)
B = np.matrix([[-1., 2., 4.], [1., 8., 6.]])
print("A * B= \n", np.multiply(A,B))

#行列Aの転置
print("A^T= \n", A.T)
print("A^T= \n", np.transpose(A,axes=(1,0)))
print("A^T= \n", np.swapaxes(A,1,0))

#複素行列のエルミート積
A = np.matrix([[3., 1.+2.j, 2.+3.j], [2., 3.-4.j, 1.+3.j]])
print("A= \n", A)
print("A^H= \n", A.H)
print("A^H= \n", np.swapaxes(np.conjugate(A),1, 0))

#行列の積に対するエルミート転置
A = np.matrix([[3., 1.+2.j, 2.+3.j], [2., 3.-4.j, 1.+3.j]])
B = np.matrix([[4.+4.j, 2.-3.j], [-1.+1.j, 3.-2.j], [1.+3.j, 5.+5j]])
print("(AB)^H= \n", (np.matmul(A,B)).H)
print("B^H A^H= \n", np.matmul(B.H, A.H))

#単位行列
I = np.eye(N=3)
print("I = \n", I)

行列Aの大きさ(M行， N行):  (2, 3)
A= 
 [[3. 1. 2.]
 [2. 3. 1.]]
cA= 
 [[6. 2. 4.]
 [4. 6. 2.]]
A + B= 
 [[ 2.  3.  6.]
 [ 3. 11.  7.]]
AB= 
 [[13. 19.]
 [ 6. 18.]]
AB= 
 [[13. 19.]
 [ 6. 18.]]
A * B= 
 [[-3.  2.  8.]
 [ 2. 24.  6.]]
A^T= 
 [[3. 2.]
 [1. 3.]
 [2. 1.]]
A^T= 
 [[3. 2.]
 [1. 3.]
 [2. 1.]]
A^T= 
 [[3. 2.]
 [1. 3.]
 [2. 1.]]
A= 
 [[3.+0.j 1.+2.j 2.+3.j]
 [2.+0.j 3.-4.j 1.+3.j]]
A^H= 
 [[3.-0.j 2.-0.j]
 [1.-2.j 3.+4.j]
 [2.-3.j 1.-3.j]]
A^H= 
 [[3.-0.j 2.-0.j]
 [1.-2.j 3.+4.j]
 [2.-3.j 1.-3.j]]
(AB)^H= 
 [[ 2.-20.j  1.-21.j]
 [ 8.-20.j -5. +4.j]]
B^H A^H= 
 [[ 2.-20.j  1.-21.j]
 [ 8.-20.j -5. +4.j]]
I = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3次元以上の配列のことをテンソルと呼ぶ，

時間（フレーム）・周波数ごとの行列$A_{lk}$と時間に依存しない周波数ごとの行列$B_k$の行列の積をとり，行列＄C_{lk}＄を以下のように計算する場合を考える．
$$
C_{lk} = A_{lk} B_k
$$
このようなテンソルの積を計算する際に有効な計算方法がアインシュタインの縮約記法である．この記法にしたがって計算を行う関数がはeinsumであり，NumPyに定義されている．
先述の式を例にとって，アインシュタインの縮約記法を用いてみる．行列$A_{lk}$を$M$行$R$列，行列$B_k$を$R$行$N$列の行列とする．このとき，要素ごとに書くと$C$の$m$行$n$列の要素は，
$$
C_{lkmn} = \sum_{r} A_{lkmr} B_{krn}
$$
となる．ここで行列の積の計算は要素の5つのインデックス$l,k,m,r,n$ののかの一つについて和をとる計算とみることができる．

具体的には$A$と$B$のインデックスには$k$と$r$が重なっている．一方で$C$のインデックスの中には$k$はあるが$r$は存在していない．つまり，掛け算を行うインデックスの中で重なっている部分インデックスかつ出力されるインデックスにないインデックスについて和を取ればよいことになる．

アインシュタインの縮約記法ではどのように掛け算を行うのかのルールを入力のインデックスと出力のインデックスの形式を与えることで教える．上記の例場合，$lkmr,krn\rightarrow lkmn$と記述できる．

また，行列$C$を計算する際に$A_{lk}$と$B_k$を掛けたものを時間方向に和をとるように計算したい場合は次の式で表せられる．
$$
C_k = \sum_{l} A_{lk}B_k
$$
これを要素ごとに記述する場合，
$$
C_{kmn} = \sum_{l, r} A_{lkmr} B_{krn}
$$
となる．この場合，縮約記法では$lkmr,krn\rightarrow kmn$と表すことができ，単純に和をとる場合でも出力インデックスをひとつ減らすだけで簡単に表現できる．

ところで次のような注意も必要である．$M$行$N$列の行列積を$mn,nm\rightarrow mn$と書いてしまった場合，これはアダマール積を表すことになるので意図した動作にならないことがある．一般的なアダマール積の表し方は行列$A_{lk}$を$M$行$N$列，行列$B_k$を$M$行$N$列の行列とした場合，
$$
C_{lkmn} = A_{lkmn}B_{kmn}
$$
で表されるので，$lkmn,kmn\rightarrow lkmn$と縮約される．掛け算を行うインデックの中で重なっているインデックスはあるものの，出力されるインデックスで欠けるものがないため，和をとることなく，要素ごとの積の演算になる．