In [2]:
import numpy as np

In [8]:
#行列Aの定義
A = np.matrix([[3., 1., 2.], [2., 3., 1.]])

print("行列Aの大きさ(M行， N行): ", np.shape(A))
print("A= \n", A)

#スカラー倍
c =2.
print("cA= \n",c* A)

#行列Aに行列Bを足す
B = np.matrix([[-1., 2., 4.], [1., 8., 6.]])
print("A + B= \n", A+B)

#行列Aに行列Bを掛ける
B = np.matrix([[4., 2.], [-1., 3.], [1., 5.]])
print("AB= \n", np.matmul(A,B))
print("AB= \n", np.einsum("mk,kn->mn",A,B))

#行列Aと行列Bのアダマール積(要素ごとの積)
B = np.matrix([[-1., 2., 4.], [1., 8., 6.]])
print("A * B= \n", np.multiply(A,B))

#行列Aの転置
print("A^T= \n", A.T)
print("A^T= \n", np.transpose(A,axes=(1,0)))
print("A^T= \n", np.swapaxes(A,1,0))

#複素行列のエルミート積
A = np.matrix([[3., 1.+2.j, 2.+3.j], [2., 3.-4.j, 1.+3.j]])
print("A= \n", A)
print("A^H= \n", A.H)
print("A^H= \n", np.swapaxes(np.conjugate(A),1, 0))

#行列の積に対するエルミート転置
A = np.matrix([[3., 1.+2.j, 2.+3.j], [2., 3.-4.j, 1.+3.j]])
B = np.matrix([[4.+4.j, 2.-3.j], [-1.+1.j, 3.-2.j], [1.+3.j, 5.+5j]])
print("(AB)^H= \n", (np.matmul(A,B)).H)
print("B^H A^H= \n", np.matmul(B.H, A.H))

#単位行列
I = np.eye(N=3)
print("I = \n", I)

行列Aの大きさ(M行， N行):  (2, 3)
A= 
 [[3. 1. 2.]
 [2. 3. 1.]]
cA= 
 [[6. 2. 4.]
 [4. 6. 2.]]
A + B= 
 [[ 2.  3.  6.]
 [ 3. 11.  7.]]
AB= 
 [[13. 19.]
 [ 6. 18.]]
AB= 
 [[13. 19.]
 [ 6. 18.]]
A * B= 
 [[-3.  2.  8.]
 [ 2. 24.  6.]]
A^T= 
 [[3. 2.]
 [1. 3.]
 [2. 1.]]
A^T= 
 [[3. 2.]
 [1. 3.]
 [2. 1.]]
A^T= 
 [[3. 2.]
 [1. 3.]
 [2. 1.]]
A= 
 [[3.+0.j 1.+2.j 2.+3.j]
 [2.+0.j 3.-4.j 1.+3.j]]
A^H= 
 [[3.-0.j 2.-0.j]
 [1.-2.j 3.+4.j]
 [2.-3.j 1.-3.j]]
A^H= 
 [[3.-0.j 2.-0.j]
 [1.-2.j 3.+4.j]
 [2.-3.j 1.-3.j]]
(AB)^H= 
 [[ 2.-20.j  1.-21.j]
 [ 8.-20.j -5. +4.j]]
B^H A^H= 
 [[ 2.-20.j  1.-21.j]
 [ 8.-20.j -5. +4.j]]
I = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3次元以上の配列のことをテンソルと呼ぶ，

時間（フレーム）・周波数ごとの行列$A_{lk}$と時間に依存しない周波数ごとの行列$B_k$の行列の積をとり，行列$C_{lk}$を以下のように計算する場合を考える．
$$
C_{lk} = A_{lk} B_k
$$
このようなテンソルの積を計算する際に有効な計算方法がアインシュタインの縮約記法である．この記法にしたがって計算を行う関数がはeinsumであり，NumPyに定義されている．
先述の式を例にとって，アインシュタインの縮約記法を用いてみる．行列$A_{lk}$を$M$行$R$列，行列$B_k$を$R$行$N$列の行列とする．このとき，要素ごとに書くと$C$の$m$行$n$列の要素は，
$$
C_{lkmn} = \sum_{r} A_{lkmr} B_{krn}
$$
となる．ここで行列の積の計算は要素の5つのインデックス$l,k,m,r,n$ののかの一つについて和をとる計算とみることができる．

具体的には$A$と$B$のインデックスには$k$と$r$が重なっている．一方で$C$のインデックスの中には$k$はあるが$r$は存在していない．つまり，掛け算を行うインデックスの中で重なっている部分インデックスかつ出力されるインデックスにないインデックスについて和を取ればよいことになる．

アインシュタインの縮約記法ではどのように掛け算を行うのかのルールを入力のインデックスと出力のインデックスの形式を与えることで教える．上記の例場合，$lkmr,krn\rightarrow lkmn$と記述できる．

また，行列$C$を計算する際に$A_{lk}$と$B_k$を掛けたものを時間方向に和をとるように計算したい場合は次の式で表せられる．
$$
C_k = \sum_{l} A_{lk}B_k
$$
これを要素ごとに記述する場合，
$$
C_{kmn} = \sum_{l, r} A_{lkmr} B_{krn}
$$
となる．この場合，縮約記法では$lkmr,krn\rightarrow kmn$と表すことができ，単純に和をとる場合でも出力インデックスをひとつ減らすだけで簡単に表現できる．

ところで次のような注意も必要である．$M$行$N$列の行列積を$mn,nm\rightarrow mn$と書いてしまった場合，これはアダマール積を表すことになるので意図した動作にならないことがある．一般的なアダマール積の表し方は行列$A_{lk}$を$M$行$N$列，行列$B_k$を$M$行$N$列の行列とした場合，
$$
C_{lkmn} = A_{lkmn}B_{kmn}
$$
で表されるので，$lkmn,kmn\rightarrow lkmn$と縮約される．掛け算を行うインデックの中で重なっているインデックスはあるものの，出力されるインデックスで欠けるものがないため，和をとることなく，要素ごとの積の演算になる．

In [2]:
import numpy as np

In [3]:
np.random.seed(0)
L = 10
K = 5
M = 3
R  = 3
N = 3

A = np.random.uniform(size=L*K*M*R)+np.random.uniform(size=L*K*M*R)*1.j
A = np.reshape(A,(L,K,M,R))

B = np.random.uniform(size = K*R*N)+np.random.uniform(size = K*R*N)*1.j
B = np.reshape(B,(K,R,N))

C = np.einsum("lkmr, krn->lkmn",A,B)

print("shape(C): ",np.shape(C))

print("A(0,0)B(0,0) = \n", np.matmul(A[0,0,...],B[0,...]))
print("C(0,0) = \n", C[0,0,...])

C = np.einsum("lkmr,krn->kmn",A,B)

print("shape(C): ",np.shape(C))

for l in range(L):
    if l ==0:
        C_2 = np.matmul(A[1,0,...], B[0,...])
    else:
        C_2 = C_2+np.matmul(A[1,0,...], B[0,...])

print("C_2(0) = \n", C_2)
print("C(0) = \n", C[0,...])

C = np.einsum("lkmn,kmn->lkmn", A,B)

print("shape(C): ",np.shape(C))

print("A(0,0)B(0,0) = \n", np.multiply(A[0,0,...],B[0,...]))
print("C(0,0) = \n", C[0,0,...])

shape(C):  (10, 5, 3, 3)
A(0,0)B(0,0) = 
 [[-0.49715528+1.60739814j -0.0430694 +2.13098867j  0.49058998+1.53302537j]
 [-0.40774965+1.27706091j -0.11232905+1.78980525j  0.30717926+1.39995875j]
 [-0.44493154+2.37398823j  0.59400714+1.73358933j  0.62369562+0.94900167j]]
C(0,0) = 
 [[-0.49715528+1.60739814j -0.0430694 +2.13098867j  0.49058998+1.53302537j]
 [-0.40774965+1.27706091j -0.11232905+1.78980525j  0.30717926+1.39995875j]
 [-0.44493154+2.37398823j  0.59400714+1.73358933j  0.62369562+0.94900167j]]
shape(C):  (5, 3, 3)
C_2(0) = 
 [[-2.35336941 +7.82688466j -1.70782093+13.02305254j
   0.50428594 +8.54846993j]
 [-4.01774577+11.86760458j -0.22125378+12.49210252j
   2.16939561 +9.22601826j]
 [-8.02370548+13.78825217j  2.34797488+19.78310425j
   5.60605852+10.84894474j]]
C(0) = 
 [[-3.961214  +14.08164414j -0.02424697+16.96557508j
   3.57699604+11.04347156j]
 [-5.11705802+15.03435616j -0.89518857+18.20029068j
   2.40292593+12.18576631j]
 [-5.42651683+15.55774111j -0.25094293+15.58870789j
 

アインシュタイン縮約記法では入力は2つ以上でも扱うことが出来る．例えば，
$$
D_k = \sum_{l} A_{lk}B_k C_l
$$
という計算を行う場合では$lkmr,krs,lsn \rightarrow kmn$と表すことができる．

　正方行列$A$に対して，以下の関係を満たす行列$B$を逆行列と呼ぶ．
$$
AB = BA = I
$$
このような逆行列を$A^{-1}$と書く．
また，逆行列が転置行列と一致するような場合にはこの逆行列を直行行列と呼ぶ．
つまり以下の関係が成り立つ．
$$
AA^T = I
$$
また，逆行列がエルミート転置行列と一致する場合，この逆行列をユニタリ行列と呼ぶ．
ここでは，
$$
AA^H = I
$$
が成り立つ．

逆行列が成立する条件として行列式が0ではないときである．ここで行列式の出番である．一般に，行列式は正方行列の大きさを表すような量である．正方行列$A$の行列式を$\mathrm{det}A$と表す．ここで(m,n) = (2, 2)の正方行列$A$の行列式は
$$
\mathrm{det}A = a_{1, 1}a_{2, 2} - a_{1, 2}a_{2, 1}
$$
で計算が可能である．
これを一般化した$M$行$M$列の正方行列$A$の行列式は
$$
\mathrm{det}A = \sum_{\sigma \in S_M} \mathrm{sgn}(\sigma) \prod_{i = 1}^{M} a_{i, \sigma(i)}
$$
と表すことができる．$S_M$は$M$個の数の並び替えの全ての種類を集めた集合であり，$\mathrm{sgn}$は並び替えの回数が奇数なら$-1$，偶数なら$1$になる記号である．

また以下の性質が挙げられる．
\begin{eqnarray*}
\mathrm{det} cA = c^M \mathrm{det}A\\
\mathrm{det} AB = \mathrm{det}A\mathrm{det}B\\
\mathrm{det}A^T = \mathrm{det}A \\
\mathrm{det}A^H = (\mathrm{det}A)^*
\end{eqnarray*}

In [2]:
import numpy as np

In [6]:
np.random.seed(0)

L = 10
M = 3
N = 3

A = np.random.uniform(size = L*M*N)+np.random.uniform(size = L*M*N)*1.j
A = np.reshape(A, (L, M, N))

detA = np.linalg.det(A)
print("detA(0): ",detA[0])
det3A = np.linalg.det(3*A)
print("det3A(0): ",det3A[0])

detA(0):  (0.5026136129571367+0.020264008179737707j)
det3A(0):  (13.570567549842696+0.5471282208529206j)


In [8]:
A_inv = np.linalg.inv(A)

AA_inv = np.einsum("lmk,lkn->lmn",A, A_inv)
print("単位行列？ : \n", AA_inv[0])

A_invA = np.einsum("lmk,lkn->lmn", A_inv, A)
print("単位行列？ : \n", A_invA[0])

単位行列？ : 
 [[ 1.00000000e+00+5.55111512e-17j  1.11022302e-16+0.00000000e+00j
  -1.11022302e-16+1.11022302e-16j]
 [ 0.00000000e+00-1.11022302e-16j  1.00000000e+00+1.11022302e-16j
  -5.55111512e-17+0.00000000e+00j]
 [-1.11022302e-16+2.22044605e-16j  0.00000000e+00+2.22044605e-16j
   1.00000000e+00+2.22044605e-16j]]
単位行列？ : 
 [[ 1.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   5.55111512e-17-1.11022302e-16j]
 [ 1.11022302e-16-1.11022302e-16j  1.00000000e+00+0.00000000e+00j
   0.00000000e+00+5.55111512e-17j]
 [-1.11022302e-16+2.77555756e-16j  0.00000000e+00+2.22044605e-16j
   1.00000000e+00+3.33066907e-16j]]


In [5]:
A_inv = np.linalg.pinv(A)

AA_inv = np.einsum("lmk,lkn->lmn",A, A_inv)
print("単位行列？ : \n", AA_inv[0])

A_invA = np.einsum("lmk,lkn->lmn",A_inv, A)
print("単位行列？ : \n", A_invA[0])

単位行列？ : 
 [[ 1.00000000e+00+0.00000000e+00j  9.99200722e-16-7.77156117e-16j
  -1.11022302e-16+4.44089210e-16j]
 [-1.11022302e-16-3.88578059e-16j  1.00000000e+00+1.11022302e-16j
  -1.11022302e-16+0.00000000e+00j]
 [ 2.77555756e-16-2.22044605e-16j  4.44089210e-16+1.11022302e-16j
   1.00000000e+00+3.33066907e-16j]]
単位行列？ : 
 [[ 1.00000000e+00+3.33066907e-16j -2.77555756e-17+1.11022302e-16j
  -3.33066907e-16+1.11022302e-16j]
 [ 6.66133815e-16-5.68989300e-16j  1.00000000e+00-1.66533454e-16j
   1.11022302e-16-2.22044605e-16j]
 [ 4.44089210e-16+4.99600361e-16j  3.33066907e-16+2.22044605e-16j
   1.00000000e+00+2.22044605e-16j]]


$M$個の要素を持つベクトル$\textbf{b}$を以下のように定義する．
$$
\textbf{b} = 
\begin{pmatrix}
b_1\\
\vdots \\
b_m \\
\vdots \\
b_M
\end{pmatrix}
$$
$M$行$N$列の行列$A$に$N$個の要素を持つベクトル$\textbf{b}$を掛けると$M$個の要素を持つベクトル$\textbf{c}$が作られる．この計算は以下のように表される．
$$
\textbf{c} = \textbf{Ab} = 
\begin{pmatrix}
a_{11} & \cdots & a_{1n} & \cdots & a_{1N}\\
\vdots & \ddots &        &        & \vdots \\
a_{m1} &        & a_{mn} &        & a_{mN} \\
\vdots &        &        & \ddots & \vdots \\
a_{M1} & \cdots & a_{Mn} & \cdots & a_{MN}
\end{pmatrix}
\begin{pmatrix}
b_1\\
\vdots \\
b_m \\
\vdots \\
b_M
\end{pmatrix}
=
\begin{pmatrix}
\sum_{n=1}^{N} a_{1n}b_n\\
\vdots \\
\sum_{n=1}^{N} a_{mn}b_n \\
\vdots \\
\sum_{n=1}^{N} a_{Mn}b_n
\end{pmatrix}
$$

In [2]:
import numpy as np

In [3]:
A = np.matrix([[3., 1., 2.], [2., 3., 1.]])

b = np.array([2., 1., 4.])

print("A = \n", A)

print("b = \n", b)

print("Ab = \n", np.dot(A,b))

A = 
 [[3. 1. 2.]
 [2. 3. 1.]]
b = 
 [2. 1. 4.]
Ab = 
 [[15. 11.]]


$M$個の要素を持つベクトル$\textbf{b}$とベクトル$\textbf{c}$の内積を次のように定義する．

ベクトルが実ベクトルの場合，
$$
d = \textbf{b}^T\textbf{c} = \sum_{m=1}^{M}b_m c_m
$$
となり，複素ベクトルの場合，
$$
d = \textbf{b}^H\textbf{c} = \sum_{m=1}^{M}b^*_m c_m
$$
これを行列の積の特殊な場合と考えることができる．つまり1行M列の行列とM行1列の行列の積と見ることができる．
また，ベクトル$\textbf{b}$とベクトル$\textbf{c}$の内積$d$が0となる場合，ベクトル$\textbf{b}$とベクトル$\textbf{c}$は直行するという．

次に同じベクトル$\textbf{b}$の内積計算を示す．実ベクトルの場合，
$$
d = \textbf{b}^T\textbf{b} = \sum_{m=1}^{M}|b_m|^2
$$
この時，$\sqrt{d}$はベクトル$\textbf{b}$の大きさを表す量となる．信号処理では各要素を2乗して足した後$\sqrt$を取ることで計算されるベクトルの大きさを$L_2$ノルムと呼ぶ．ここから一般化して$L_p$ノルムを以下のように定義する．
$$
||\textbf{b}||_p = \sqrt[n]{\sum_{m=1}^{M}|b_m|^p}
$$
 ここで$L_2$ノルムが0となるベクトルを零ベクトル，$L_2$ノルムが1となるベクトルを単位ベクトルと呼ぶ．

In [5]:
import numpy as np

In [11]:
a = np.array([3.+2.j, 1.-1.j, 2.+2.j])
print(a)
b = np.array([2.+5.j, 1.-1J, 4.+1.j])
print(b)

print("a^Hb=", np.inner(np.conjugate(a),b))

print("a^Ha=", np.inner(np.conjugate(a),a))

[3.+2.j 1.-1.j 2.+2.j]
[2.+5.j 1.-1.j 4.+1.j]
a^Hb= (28+5j)
a^Ha= (23+0j)


逆行列が存在するか重要な判定法としての線形独立性について述べる．まず，行列$\textbf{A}$の列ベクトル$\textbf{a}_m$を以下のように定義する．
$$
\textbf{a}_m = 
\begin{pmatrix}
a_1m\\
\vdots \\
a_nm \\
\vdots \\
a_Nm
\end{pmatrix}
$$
つまり，
$$
\textbf{A} = [a_1 \cdots a_m \cdots a_M]
$$
と表すことができる．ここで逆行列が存在するということは行列式が0でないことである．つまり，行列の列ベクトルが線形独立であることである．

行列が線形独立ということは列ベクトル$a_m$が$m$以外の列ベクトルの線形和で書くことができないということである．
$$
\sum_{m=1}^{M}\alpha_m\textbf{a}_m = 0
$$
となるならば，$\alpha_m = 0$しかありえない．M次の正方行列では最大M個の線形独立なベクトルが存在する．仮にM+1個のベクトルを選んでくるとすると，必ず1つは線形独立でないベクトルが存在する．任意のベクトル$\textbf{b}$はM個の線形独立なベクトルの線形和で表すことができる．
$$
\textbf{b} = \sum_{m=1}^{M}\beta_m\textbf{a}_m
$$
このとき，$\beta_m$は$\textbf{b}$ごとに1通りしか存在しないことになる．また，M次元の任意ベクトルはM個の線形独立なベクトルの線形和として書くことができる．つまり，M次元のベクトルはM個の基底で分解できるということである．